//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace TKC_Silverlight.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSTopSoap")]
    public interface WSTopSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAllCampaignOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TopObject))]
        System.IAsyncResult BeginGetAllCampaignOnline(System.AsyncCallback callback, object asyncState);
        
        TKC_Silverlight.ServiceReference1.Campaign[] EndGetAllCampaignOnline(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAllCampaignRptOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TopObject))]
        System.IAsyncResult BeginGetAllCampaignRptOnline(string strDateStart, string strDateEnd, System.AsyncCallback callback, object asyncState);
        
        TKC_Silverlight.ServiceReference1.EntityCampaignReport[] EndGetAllCampaignRptOnline(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetItemKeywords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TopObject))]
        System.IAsyncResult BeginGetItemKeywords(string itemIdOrUrl, System.AsyncCallback callback, object asyncState);
        
        TKC_Silverlight.ServiceReference1.EntityWordData[] EndGetItemKeywords(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetProvidedCatInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TopObject))]
        System.IAsyncResult BeginGetProvidedCatInfo(System.AsyncCallback callback, object asyncState);
        
        string EndGetProvidedCatInfo(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Campaign : TopObject {
        
        private long campaign_idField;
        
        private string create_timeField;
        
        private string modified_timeField;
        
        private string nickField;
        
        private string online_statusField;
        
        private string settle_reasonField;
        
        private string settle_statusField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long campaign_id {
            get {
                return this.campaign_idField;
            }
            set {
                this.campaign_idField = value;
                this.RaisePropertyChanged("campaign_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string create_time {
            get {
                return this.create_timeField;
            }
            set {
                this.create_timeField = value;
                this.RaisePropertyChanged("create_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string modified_time {
            get {
                return this.modified_timeField;
            }
            set {
                this.modified_timeField = value;
                this.RaisePropertyChanged("modified_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
                this.RaisePropertyChanged("nick");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string online_status {
            get {
                return this.online_statusField;
            }
            set {
                this.online_statusField = value;
                this.RaisePropertyChanged("online_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string settle_reason {
            get {
                return this.settle_reasonField;
            }
            set {
                this.settle_reasonField = value;
                this.RaisePropertyChanged("settle_reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string settle_status {
            get {
                return this.settle_statusField;
            }
            set {
                this.settle_statusField = value;
                this.RaisePropertyChanged("settle_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Campaign))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class TopObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityWordData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string wordField;
        
        private long clickField;
        
        private double competitionField;
        
        private double costField;
        
        private double rateField;
        
        private double cpcField;
        
        private double ctrField;
        
        private double directpayField;
        
        private long directpaycountField;
        
        private long favitemcountField;
        
        private long favshopcountField;
        
        private long totalfavcountField;
        
        private long impressionsField;
        
        private double indirectpayField;
        
        private long indirectpaycountField;
        
        private double roiField;
        
        private long totalpaycountField;
        
        private double totalpayField;
        
        private double similarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long click {
            get {
                return this.clickField;
            }
            set {
                this.clickField = value;
                this.RaisePropertyChanged("click");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double competition {
            get {
                return this.competitionField;
            }
            set {
                this.competitionField = value;
                this.RaisePropertyChanged("competition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double cpc {
            get {
                return this.cpcField;
            }
            set {
                this.cpcField = value;
                this.RaisePropertyChanged("cpc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double ctr {
            get {
                return this.ctrField;
            }
            set {
                this.ctrField = value;
                this.RaisePropertyChanged("ctr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double directpay {
            get {
                return this.directpayField;
            }
            set {
                this.directpayField = value;
                this.RaisePropertyChanged("directpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long directpaycount {
            get {
                return this.directpaycountField;
            }
            set {
                this.directpaycountField = value;
                this.RaisePropertyChanged("directpaycount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long favitemcount {
            get {
                return this.favitemcountField;
            }
            set {
                this.favitemcountField = value;
                this.RaisePropertyChanged("favitemcount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long favshopcount {
            get {
                return this.favshopcountField;
            }
            set {
                this.favshopcountField = value;
                this.RaisePropertyChanged("favshopcount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long totalfavcount {
            get {
                return this.totalfavcountField;
            }
            set {
                this.totalfavcountField = value;
                this.RaisePropertyChanged("totalfavcount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long impressions {
            get {
                return this.impressionsField;
            }
            set {
                this.impressionsField = value;
                this.RaisePropertyChanged("impressions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double indirectpay {
            get {
                return this.indirectpayField;
            }
            set {
                this.indirectpayField = value;
                this.RaisePropertyChanged("indirectpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public long indirectpaycount {
            get {
                return this.indirectpaycountField;
            }
            set {
                this.indirectpaycountField = value;
                this.RaisePropertyChanged("indirectpaycount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double roi {
            get {
                return this.roiField;
            }
            set {
                this.roiField = value;
                this.RaisePropertyChanged("roi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public long totalpaycount {
            get {
                return this.totalpaycountField;
            }
            set {
                this.totalpaycountField = value;
                this.RaisePropertyChanged("totalpaycount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double totalpay {
            get {
                return this.totalpayField;
            }
            set {
                this.totalpayField = value;
                this.RaisePropertyChanged("totalpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double similar {
            get {
                return this.similarField;
            }
            set {
                this.similarField = value;
                this.RaisePropertyChanged("similar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityCampaignReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long campaign_idField;
        
        private string campaign_nameField;
        
        private string campaign_statusField;
        
        private string dateField;
        
        private int impressionsField;
        
        private int clickField;
        
        private decimal costField;
        
        private decimal ctrField;
        
        private decimal cpcField;
        
        private decimal directpayField;
        
        private decimal indirectpayField;
        
        private decimal totalpayField;
        
        private decimal roiField;
        
        private int totalpaycountField;
        
        private int directpaycountField;
        
        private int indirectpaycountField;
        
        private int totalfavcountField;
        
        private int favitemcountField;
        
        private int favshopcountField;
        
        private decimal rateField;
        
        private decimal avgposField;
        
        private string sourceField;
        
        private string nickField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long campaign_id {
            get {
                return this.campaign_idField;
            }
            set {
                this.campaign_idField = value;
                this.RaisePropertyChanged("campaign_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string campaign_name {
            get {
                return this.campaign_nameField;
            }
            set {
                this.campaign_nameField = value;
                this.RaisePropertyChanged("campaign_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string campaign_status {
            get {
                return this.campaign_statusField;
            }
            set {
                this.campaign_statusField = value;
                this.RaisePropertyChanged("campaign_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int impressions {
            get {
                return this.impressionsField;
            }
            set {
                this.impressionsField = value;
                this.RaisePropertyChanged("impressions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int click {
            get {
                return this.clickField;
            }
            set {
                this.clickField = value;
                this.RaisePropertyChanged("click");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal ctr {
            get {
                return this.ctrField;
            }
            set {
                this.ctrField = value;
                this.RaisePropertyChanged("ctr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal cpc {
            get {
                return this.cpcField;
            }
            set {
                this.cpcField = value;
                this.RaisePropertyChanged("cpc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal directpay {
            get {
                return this.directpayField;
            }
            set {
                this.directpayField = value;
                this.RaisePropertyChanged("directpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal indirectpay {
            get {
                return this.indirectpayField;
            }
            set {
                this.indirectpayField = value;
                this.RaisePropertyChanged("indirectpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal totalpay {
            get {
                return this.totalpayField;
            }
            set {
                this.totalpayField = value;
                this.RaisePropertyChanged("totalpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal roi {
            get {
                return this.roiField;
            }
            set {
                this.roiField = value;
                this.RaisePropertyChanged("roi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int totalpaycount {
            get {
                return this.totalpaycountField;
            }
            set {
                this.totalpaycountField = value;
                this.RaisePropertyChanged("totalpaycount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int directpaycount {
            get {
                return this.directpaycountField;
            }
            set {
                this.directpaycountField = value;
                this.RaisePropertyChanged("directpaycount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int indirectpaycount {
            get {
                return this.indirectpaycountField;
            }
            set {
                this.indirectpaycountField = value;
                this.RaisePropertyChanged("indirectpaycount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int totalfavcount {
            get {
                return this.totalfavcountField;
            }
            set {
                this.totalfavcountField = value;
                this.RaisePropertyChanged("totalfavcount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int favitemcount {
            get {
                return this.favitemcountField;
            }
            set {
                this.favitemcountField = value;
                this.RaisePropertyChanged("favitemcount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int favshopcount {
            get {
                return this.favshopcountField;
            }
            set {
                this.favshopcountField = value;
                this.RaisePropertyChanged("favshopcount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal avgpos {
            get {
                return this.avgposField;
            }
            set {
                this.avgposField = value;
                this.RaisePropertyChanged("avgpos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
                this.RaisePropertyChanged("nick");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSTopSoapChannel : TKC_Silverlight.ServiceReference1.WSTopSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCampaignOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCampaignOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TKC_Silverlight.ServiceReference1.Campaign[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TKC_Silverlight.ServiceReference1.Campaign[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCampaignRptOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCampaignRptOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TKC_Silverlight.ServiceReference1.EntityCampaignReport[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TKC_Silverlight.ServiceReference1.EntityCampaignReport[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetItemKeywordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemKeywordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TKC_Silverlight.ServiceReference1.EntityWordData[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TKC_Silverlight.ServiceReference1.EntityWordData[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProvidedCatInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProvidedCatInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTopSoapClient : System.ServiceModel.ClientBase<TKC_Silverlight.ServiceReference1.WSTopSoap>, TKC_Silverlight.ServiceReference1.WSTopSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllCampaignOnlineDelegate;
        
        private EndOperationDelegate onEndGetAllCampaignOnlineDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCampaignOnlineCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllCampaignRptOnlineDelegate;
        
        private EndOperationDelegate onEndGetAllCampaignRptOnlineDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCampaignRptOnlineCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetItemKeywordsDelegate;
        
        private EndOperationDelegate onEndGetItemKeywordsDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemKeywordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProvidedCatInfoDelegate;
        
        private EndOperationDelegate onEndGetProvidedCatInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetProvidedCatInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WSTopSoapClient() {
        }
        
        public WSTopSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTopSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTopSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTopSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetAllCampaignOnlineCompletedEventArgs> GetAllCampaignOnlineCompleted;
        
        public event System.EventHandler<GetAllCampaignRptOnlineCompletedEventArgs> GetAllCampaignRptOnlineCompleted;
        
        public event System.EventHandler<GetItemKeywordsCompletedEventArgs> GetItemKeywordsCompleted;
        
        public event System.EventHandler<GetProvidedCatInfoCompletedEventArgs> GetProvidedCatInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TKC_Silverlight.ServiceReference1.WSTopSoap.BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string TKC_Silverlight.ServiceReference1.WSTopSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TKC_Silverlight.ServiceReference1.WSTopSoap.BeginGetAllCampaignOnline(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllCampaignOnline(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TKC_Silverlight.ServiceReference1.Campaign[] TKC_Silverlight.ServiceReference1.WSTopSoap.EndGetAllCampaignOnline(System.IAsyncResult result) {
            return base.Channel.EndGetAllCampaignOnline(result);
        }
        
        private System.IAsyncResult OnBeginGetAllCampaignOnline(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).BeginGetAllCampaignOnline(callback, asyncState);
        }
        
        private object[] OnEndGetAllCampaignOnline(System.IAsyncResult result) {
            TKC_Silverlight.ServiceReference1.Campaign[] retVal = ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).EndGetAllCampaignOnline(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCampaignOnlineCompleted(object state) {
            if ((this.GetAllCampaignOnlineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCampaignOnlineCompleted(this, new GetAllCampaignOnlineCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllCampaignOnlineAsync() {
            this.GetAllCampaignOnlineAsync(null);
        }
        
        public void GetAllCampaignOnlineAsync(object userState) {
            if ((this.onBeginGetAllCampaignOnlineDelegate == null)) {
                this.onBeginGetAllCampaignOnlineDelegate = new BeginOperationDelegate(this.OnBeginGetAllCampaignOnline);
            }
            if ((this.onEndGetAllCampaignOnlineDelegate == null)) {
                this.onEndGetAllCampaignOnlineDelegate = new EndOperationDelegate(this.OnEndGetAllCampaignOnline);
            }
            if ((this.onGetAllCampaignOnlineCompletedDelegate == null)) {
                this.onGetAllCampaignOnlineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCampaignOnlineCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllCampaignOnlineDelegate, null, this.onEndGetAllCampaignOnlineDelegate, this.onGetAllCampaignOnlineCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TKC_Silverlight.ServiceReference1.WSTopSoap.BeginGetAllCampaignRptOnline(string strDateStart, string strDateEnd, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllCampaignRptOnline(strDateStart, strDateEnd, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TKC_Silverlight.ServiceReference1.EntityCampaignReport[] TKC_Silverlight.ServiceReference1.WSTopSoap.EndGetAllCampaignRptOnline(System.IAsyncResult result) {
            return base.Channel.EndGetAllCampaignRptOnline(result);
        }
        
        private System.IAsyncResult OnBeginGetAllCampaignRptOnline(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string strDateStart = ((string)(inValues[0]));
            string strDateEnd = ((string)(inValues[1]));
            return ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).BeginGetAllCampaignRptOnline(strDateStart, strDateEnd, callback, asyncState);
        }
        
        private object[] OnEndGetAllCampaignRptOnline(System.IAsyncResult result) {
            TKC_Silverlight.ServiceReference1.EntityCampaignReport[] retVal = ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).EndGetAllCampaignRptOnline(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCampaignRptOnlineCompleted(object state) {
            if ((this.GetAllCampaignRptOnlineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCampaignRptOnlineCompleted(this, new GetAllCampaignRptOnlineCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllCampaignRptOnlineAsync(string strDateStart, string strDateEnd) {
            this.GetAllCampaignRptOnlineAsync(strDateStart, strDateEnd, null);
        }
        
        public void GetAllCampaignRptOnlineAsync(string strDateStart, string strDateEnd, object userState) {
            if ((this.onBeginGetAllCampaignRptOnlineDelegate == null)) {
                this.onBeginGetAllCampaignRptOnlineDelegate = new BeginOperationDelegate(this.OnBeginGetAllCampaignRptOnline);
            }
            if ((this.onEndGetAllCampaignRptOnlineDelegate == null)) {
                this.onEndGetAllCampaignRptOnlineDelegate = new EndOperationDelegate(this.OnEndGetAllCampaignRptOnline);
            }
            if ((this.onGetAllCampaignRptOnlineCompletedDelegate == null)) {
                this.onGetAllCampaignRptOnlineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCampaignRptOnlineCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllCampaignRptOnlineDelegate, new object[] {
                        strDateStart,
                        strDateEnd}, this.onEndGetAllCampaignRptOnlineDelegate, this.onGetAllCampaignRptOnlineCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TKC_Silverlight.ServiceReference1.WSTopSoap.BeginGetItemKeywords(string itemIdOrUrl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItemKeywords(itemIdOrUrl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TKC_Silverlight.ServiceReference1.EntityWordData[] TKC_Silverlight.ServiceReference1.WSTopSoap.EndGetItemKeywords(System.IAsyncResult result) {
            return base.Channel.EndGetItemKeywords(result);
        }
        
        private System.IAsyncResult OnBeginGetItemKeywords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string itemIdOrUrl = ((string)(inValues[0]));
            return ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).BeginGetItemKeywords(itemIdOrUrl, callback, asyncState);
        }
        
        private object[] OnEndGetItemKeywords(System.IAsyncResult result) {
            TKC_Silverlight.ServiceReference1.EntityWordData[] retVal = ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).EndGetItemKeywords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemKeywordsCompleted(object state) {
            if ((this.GetItemKeywordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemKeywordsCompleted(this, new GetItemKeywordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemKeywordsAsync(string itemIdOrUrl) {
            this.GetItemKeywordsAsync(itemIdOrUrl, null);
        }
        
        public void GetItemKeywordsAsync(string itemIdOrUrl, object userState) {
            if ((this.onBeginGetItemKeywordsDelegate == null)) {
                this.onBeginGetItemKeywordsDelegate = new BeginOperationDelegate(this.OnBeginGetItemKeywords);
            }
            if ((this.onEndGetItemKeywordsDelegate == null)) {
                this.onEndGetItemKeywordsDelegate = new EndOperationDelegate(this.OnEndGetItemKeywords);
            }
            if ((this.onGetItemKeywordsCompletedDelegate == null)) {
                this.onGetItemKeywordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemKeywordsCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemKeywordsDelegate, new object[] {
                        itemIdOrUrl}, this.onEndGetItemKeywordsDelegate, this.onGetItemKeywordsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TKC_Silverlight.ServiceReference1.WSTopSoap.BeginGetProvidedCatInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProvidedCatInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string TKC_Silverlight.ServiceReference1.WSTopSoap.EndGetProvidedCatInfo(System.IAsyncResult result) {
            return base.Channel.EndGetProvidedCatInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetProvidedCatInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).BeginGetProvidedCatInfo(callback, asyncState);
        }
        
        private object[] OnEndGetProvidedCatInfo(System.IAsyncResult result) {
            string retVal = ((TKC_Silverlight.ServiceReference1.WSTopSoap)(this)).EndGetProvidedCatInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProvidedCatInfoCompleted(object state) {
            if ((this.GetProvidedCatInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProvidedCatInfoCompleted(this, new GetProvidedCatInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProvidedCatInfoAsync() {
            this.GetProvidedCatInfoAsync(null);
        }
        
        public void GetProvidedCatInfoAsync(object userState) {
            if ((this.onBeginGetProvidedCatInfoDelegate == null)) {
                this.onBeginGetProvidedCatInfoDelegate = new BeginOperationDelegate(this.OnBeginGetProvidedCatInfo);
            }
            if ((this.onEndGetProvidedCatInfoDelegate == null)) {
                this.onEndGetProvidedCatInfoDelegate = new EndOperationDelegate(this.OnEndGetProvidedCatInfo);
            }
            if ((this.onGetProvidedCatInfoCompletedDelegate == null)) {
                this.onGetProvidedCatInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProvidedCatInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetProvidedCatInfoDelegate, null, this.onEndGetProvidedCatInfoDelegate, this.onGetProvidedCatInfoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TKC_Silverlight.ServiceReference1.WSTopSoap CreateChannel() {
            return new WSTopSoapClientChannel(this);
        }
        
        private class WSTopSoapClientChannel : ChannelBase<TKC_Silverlight.ServiceReference1.WSTopSoap>, TKC_Silverlight.ServiceReference1.WSTopSoap {
            
            public WSTopSoapClientChannel(System.ServiceModel.ClientBase<TKC_Silverlight.ServiceReference1.WSTopSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllCampaignOnline(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllCampaignOnline", _args, callback, asyncState);
                return _result;
            }
            
            public TKC_Silverlight.ServiceReference1.Campaign[] EndGetAllCampaignOnline(System.IAsyncResult result) {
                object[] _args = new object[0];
                TKC_Silverlight.ServiceReference1.Campaign[] _result = ((TKC_Silverlight.ServiceReference1.Campaign[])(base.EndInvoke("GetAllCampaignOnline", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllCampaignRptOnline(string strDateStart, string strDateEnd, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = strDateStart;
                _args[1] = strDateEnd;
                System.IAsyncResult _result = base.BeginInvoke("GetAllCampaignRptOnline", _args, callback, asyncState);
                return _result;
            }
            
            public TKC_Silverlight.ServiceReference1.EntityCampaignReport[] EndGetAllCampaignRptOnline(System.IAsyncResult result) {
                object[] _args = new object[0];
                TKC_Silverlight.ServiceReference1.EntityCampaignReport[] _result = ((TKC_Silverlight.ServiceReference1.EntityCampaignReport[])(base.EndInvoke("GetAllCampaignRptOnline", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetItemKeywords(string itemIdOrUrl, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = itemIdOrUrl;
                System.IAsyncResult _result = base.BeginInvoke("GetItemKeywords", _args, callback, asyncState);
                return _result;
            }
            
            public TKC_Silverlight.ServiceReference1.EntityWordData[] EndGetItemKeywords(System.IAsyncResult result) {
                object[] _args = new object[0];
                TKC_Silverlight.ServiceReference1.EntityWordData[] _result = ((TKC_Silverlight.ServiceReference1.EntityWordData[])(base.EndInvoke("GetItemKeywords", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProvidedCatInfo(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetProvidedCatInfo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetProvidedCatInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetProvidedCatInfo", _args, result)));
                return _result;
            }
        }
    }
}
